# Generated by Django 3.1.4 on 2020-12-24 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20201224_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'пол', 'verbose_name_plural': 'пол'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='selection',
            field=models.CharField(choices=[('m', 'Мужской пол.'), ('w', 'Женский пол.')], default='m', max_length=1, verbose_name='Выбрать пол'),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agreement', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашении',
            },
        ),
    ]
