# Generated by Django 3.1.4 on 2020-12-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201225_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='Agreement',
            field=models.BooleanField(default=False, verbose_name='Соглашение на уведомление на почту'),
        ),
    ]
