# Generated by Django 3.1.4 on 2020-12-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(' ', '-'), ('m', 'Мужской пол.'), ('w', 'Женский пол.')], default='', max_length=1),
        ),
    ]
