# Generated by Django 3.1.4 on 2020-12-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201225_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
