# Generated by Django 3.1.4 on 2020-12-28 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20201226_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('plain_message', models.TextField(max_length=150, verbose_name='Текст сообщения')),
                ('to', models.CharField(default='vtgk12ak@gmail.com', max_length=100, verbose_name='Получатель')),
                ('from_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отправка сообщения',
                'verbose_name_plural': 'Отправки сообщений',
            },
        ),
    ]
