# Generated by Django 3.1.4 on 2020-12-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sendmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='from_email',
            field=models.EmailField(max_length=50, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='to',
            field=models.EmailField(default='vtgk12ak@gmail.com', max_length=50, verbose_name='Получатель'),
        ),
    ]
