# Generated by Django 3.1.4 on 2020-12-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201229_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendmail',
            options={'verbose_name': 'Котант', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='plain_message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Тема письма'),
        ),
    ]
