# Generated by Django 3.1.4 on 2020-12-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_article',
            field=models.ImageField(default='default-article.png', upload_to='article_images', verbose_name='Изображение статьи'),
        ),
    ]
